### ISSUE TITLE
Canvas doesn't cover width of the window

### ISSUE THREAD

**Issue by exu3** [lachlanjc/resnow#4]
Hello 👋  Resnow is awesome and it looks really cool! Is it possible to make the canvas cover the full width of the screen? I tried adding a width prop `<Snow width="100vw" />` to the component, but it had no effect.

![ezgif-4-0dddfea661ca](https://user-images.githubusercontent.com/72365100/145926461-5970fe75-89d3-4446-ad01-9531ba3ae374.gif)

**Comment by exu3** [comment]
Oops sorry I figured it out :P

**Comment by lachlanjc** [comment]
Want to link to your solution so other folks who stumble across this can use?

(Personally I'd use a window size hook from something like react-use!)
